'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Game_Main

    '''<summary>
    '''lblGameTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGameTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfImagePosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfImagePosition As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQuestionTitle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuestionTitle1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQuestionTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuestionTeam1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAnswerTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnswerTeam1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmitTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitTeam1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblBattleTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBattleTeam1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblScoreTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreTeam1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBattleTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBattleTeam2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblScoreTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreTeam2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgBattle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBattle As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblBattleTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBattleTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnRestartGame control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRestartGame As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHome As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQuestionTitle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuestionTitle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQuestionTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuestionTeam2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAnswerTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnswerTeam2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmitTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitTeam2 As Global.System.Web.UI.WebControls.Button
End Class
